openapi: 3.0.3
info:
  title: API Gestione Ordini
  version: 1.0.0
paths:
  /order:
    post:
      summary: Crea un nuovo ordine
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Ordine creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    get:
      summary: Ottieni tutti gli ordini
      operationId: getAllOrders
      responses:
        '200':
          description: Elenco di tutti gli ordini
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID dell'ordine
        customerId:
          type: string
          format: uuid
          description: ID del cliente
        product:
          type: string
          description: Prodotto dell'ordine
        quantity:
          type: integer
          description: Quantità del prodotto
        creationDate:
          type: string
          format: date-time
          description: Data di creazione dell'ordine
